title:              Ninjuku Studio
email:              hi@ninjukustudio.com
description:        A Web Development Studio Specializing in Low-Cost Company Profile Sites
author:             Ninjuku Sensei
baseurl:            "/"

# Collections
collections:
  posts:
    title: Posts
    output: true
  portfolios:
    title: Portfolios
    output: true
  services:
    title: Services
    output: true
  downloads:
    title: Downloads
    output: true
  clienteles:
    title: Clientele
    output: true
  packages:
    title: Packages
    output: true
  demos:
    title: Demos
    output: true
    
# Social Profiles
socials:
  - network: github
    url: https://github.com/ninjukustudio
  - network: instagram
    url: https://instagram.com/ninjukustudio
  - network: envelope
    url: mailto:ninjuku.desu@gmail.com
# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path: "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
