title:              Ninjuku Studio
email:              sensei@ninjuku.studio
description:        A Brand Design & Web Development Studio Tailoring Digital Presence for Professionals, Organizations, Schools, Businesses, and Events
author:             Ninjuku Sensei
baseurl:            "/"
phone:              6285787706533
message:            "Hello, Ninjuku Studio."

# Collections
collections:
  posts:
    title: Posts
    output: true
  portfolios:
    title: Portfolios
    output: true
  services:
    title: Services
    output: true
  downloads:
    title: Downloads
    output: true
  clienteles:
    title: Clientele
    output: true
  packages:
    title: Packages
    output: true
  demos:
    title: Demos
    output: true
    
# Social Profiles
socials:
  - network: github
    url: https://github.com/ninjukustudio
  - network: instagram
    url: https://instagram.com/ninjukustudio
  - network: envelope
    url: mailto:sensei@ninjuku.studio
  - network: whatsapp
    url: https://wa.me/6285787706533
# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
